const screenNames = {
  LOADING: 'LOADING',
  HOME_STACK: 'HOME_STACK',
  DRIVERS_STACK: 'DRIVERS_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  RESET_PASSWORD_SCREEN: 'RESET_PASSWORD_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  DRIVER_SCREEN: 'DRIVER_SCREEN',
  ACCOUNT_SETTING_SCREEN: 'ACCOUNT_SETTING_SCREEN',
  MAIN_TAB: 'MAIN_TAB',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',
  SCAN_QR_SCREEN: 'SCAN_QR_SCREEN',
  SCAN_QR_RESULT_SCREEN: 'SCAN_QR_RESULT_SCREEN',
  SELECT_BRANCH_SCREEN: 'SELECT_BRANCH_SCREEN',
  CHOOSE_READ_METHOD: 'CHOOSE_READ_METHOD',
  SCAN_SOCKET_QR: 'SCAN_SOCKET_QR',
};

export default screenNames;
